<Project Sdk="Dalamud.NET.Sdk/15.0.0">
  <PropertyGroup>
    <Version>1.4.0.2</Version>
    <AssemblyName>Levemetes</AssemblyName>
    <RootNamespace>TruthOrDare</RootNamespace>
    <PackageProjectUrl>https://github.com/kaerlath/Levemetes</PackageProjectUrl>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <IsPackable>false</IsPackable>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
  </PropertyGroup>
  <ItemGroup>
    <Content Include="card-back.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <Visible>true</Visible>
    </Content>
    <Content Include="DirectPrivateGameHelp.txt">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <Visible>true</Visible>
    </Content>
    <Content Include="GameInstructions.txt">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <Visible>true</Visible>
    </Content>
    <Content Include="Assets\Templates\*.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <Visible>true</Visible>
    </Content>
    <Content Include="Assets\Artwork\*.jpg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <Visible>true</Visible>
    </Content>
  </ItemGroup>
</Project>
